[package]
name = "kot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.23", features = ["derive"] }
rustyline = "15.0.0"
urlencoding = "2.1.3"
webbrowser = "1.0.3"

[dev-dependencies]
pretty_assertions = "1.4.1"
